### ISSUE TITLE
Node version compatible issue

### ISSUE THREAD

**Issue by Comment-TODO** [coderaiser/flop#3]
Node version 12.x doesn't support `require('fs/promises');`,

so it has to be `require('fs').promises;` for both Node 12.x, 14.x.

Same for your 'readify' repo, but I'll not add issue for that and I hope to be fixed too.

**Comment by coderaiser** [comment]
`require(fs/promises)` supported started from `node v14` according to [docs](https://nodejs.org/api/fs.html#fs_fs_promises_api).

Do you have an issue with `flop`? What version of nodejs are you using right now?

**Comment by Comment-TODO** [comment]
I'm using node v12 right now, and `require('fs/promises');` causes error.
 `require('fs').promises;` would be better because it can handled with v12, v14 both.

**Comment by coderaiser** [comment]
Support of node `<14` is dropped with [flop v9.0.0](https://github.com/coderaiser/flop/releases/tag/v9.0.0). Why do you need it?
